package com.wg.map_demo.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wg.map_demo.data.Orders;
import com.wg.map_demo.data.User;

import com.wg.map_demo.data.OrdersDao;
import com.wg.map_demo.data.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ordersDaoConfig;
    private final DaoConfig userDaoConfig;

    private final OrdersDao ordersDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ordersDaoConfig = daoConfigMap.get(OrdersDao.class).clone();
        ordersDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        ordersDao = new OrdersDao(ordersDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Orders.class, ordersDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        ordersDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public OrdersDao getOrdersDao() {
        return ordersDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
